#-------------------------------------------
#------------ for NRC ----------------------
# Note: NRC QA test config for automation regression test via gRPC. Please keep gRPC proto file updated and compiled before run NRC test

  # NRC via gRPC server port, default: 50051, insecure connection; secure connection port: 50052
NRCServicePort: 50051  # for gRPC connection NRC server port, default
#NRCSecureServicePort: 50052 # for gRPC secure connection NRC server port, default
#NRCServicePort: 50053  # for gRPC connection ENVOY load balancer
#NRCServicePort: 443 	# for NRaaS testing

  # NRC via gRPC server IP or hostname
NRCServiceIP: 'localhost'  # QA1 Kubernetes cluster, master node
#NRCServiceIP: mtl-nraas-vm03  # QA1 Kubernetes cluster, worker node
#NRCServiceIP: 'mtl-ce05'  # DEV Kubernetes cluster, master node
#NRCServiceIP: 'mtl-nraas-vm08'  # QA2 Kubernetes cluster, master node
#NRCServiceIP: '10.3.106.187'  # MRCP gateway QA Kubernetes cluster, master node
#NRCServiceIP: 10.3.106.38  # QA1 master node, IP
#NRCServiceIP: 10.33.12.147  # QA AKS user -> NRC on AKS cluster
#NRCServiceIP: mtl-nraas-vm20 
#NRCServiceIP: nraas.qa.cd4.private.crt.nuance.com/nuance.nrc.v1.NRC   # NRaaS staging env in CD4 endpoint
#NRCServiceIP: nraas.stage.cd4.private.crt.nuance.com/nuance.nrc.v1.NRC  # NRaaS QA env in CD4 endpoint

  # NRC test via secure connection or insecure connector settings, default: False
#NRCTestSecureConnect: True    # Must set to True for NRaaS test, optional for NRC
NRCTestSecureConnect: False    # Must set to True for NRaaS test, optional for NRC


  # NRC Kafka service port
  # Exposed to outside cluster: "31090"
  # Port for internal to cluster: "30092"
NRCKafkaPort: "31090"

  # NRC test with metadata in header. 
  # Required if NRC value: nrcConfig.authentication.enabled=True
  # otherwise set metadata to None
NRCTestMetadata: #None
  audiofileid: "12346"
  #x-nuance-client-id: "appID:mydummyappid2:geo:dev:clientName:default"
  #x-nuance-client-id: "NMDPTRIAL_karthickeyan_chockaligam_nuance_com_20200120T170008297245"
  #x-nuance-client-id: "appID:NMDPTRIAL_gang_hu_nuance_com_20221007T152710664720_origin_dev:geo:dev:clientName:default"
  x-nuance-client-id: "appID:NMDPTRIAL_gang_hu_nuance_com_20221122T160126508643_origin_qa:geo:qa:clientName:default"



  # NRC QA Apache server for test resource (uri, grammar...)
NRCTestResURL: 'http://192.168.9.18/nrc_res1/tests/'      # for case that verify grammar fetch via http, mtl-nr11mw-vm61
NRCTestResURLSecure: 'https://192.168.9.18/nrc_res1/tests/' # for cases that verify grammar fetch via https

  # NRC QA audio test params
NRCAudioPath: '/package/unarchive/Framework/nrctest/audio/'
NRCAudioBufms: 30
NRCAudioXrate: 1.0

  # NRC QA test robust re-try params:
NRCTestRetryNum: 3
NRCTestRetryWaitSec: 5

  # NRC QA test logging params, 0 - warning (regression/load), 1 -  info (regressiion), 2 - debug
NRCTestLogging: 2

# NRC QA test rerun failed testcase params, Enter the number you wish to retry
NRCTestRetryFailedTestCases: 5
#------------------------------------------------

